name = "AbstractFastHartleyTransforms"
uuid = "19a999c2-4b91-4a95-a5ef-9640c9e909f0"
authors = ["Kazunori Akiyama"]
version = "0.1.0"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
AbstractFFTs = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
